export const USERPROFILES_LOADED = 'USERPROFILES_LOADED';
export const USERPROFILE_POSTED = 'USERPROFILE_POSTED';
export const USERPROFILE_EDITED = 'USERPROFILE_EDITED';
//export const USERPROFILE_DELETED = 'COMMENT_DELETED';
export const FRIEND_UPDATED = 'FRIEND_UPDATED';

/*
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';*/
