export const STORIES_LOADED = 'STORIES_LOADED';
export const STORY_POSTED = 'STORY_POSTED';
export const STORY_EDITED = 'STORY_EDITED';
export const STORY_DELETED = 'STORY_DELETED';

export const COMMENT_POSTED = 'COMMENT_POSTED';
export const COMMENT_EDITED = 'COMMENT_EDITED';
export const COMMENT_DELETED = 'COMMENT_DELETED';

export const USERPROFILES_LOADED = 'USERPROFILES_LOADED';
export const USERPROFILE_POSTED = 'USERPROFILE_POSTED';
export const USERPROFILE_EDITED = 'USERPROFILE_EDITED';
//export const USERPROFILE_DELETED = 'COMMENT_DELETED';
export const FRIEND_UPDATED = 'FRIEND_UPDATED';

/*
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';*/
